document.writeln("<div id=\"code\"><\/div>");
document.writeln("<div id=\"code_img\"><\/div>");
document.writeln("<a id=\"gotop\" href=\"javascript:void(0)\"><\/a>");
document.writeln("<script>");
document.writeln("\/\/返回顶部");
document.writeln("function b(){");
document.writeln("  h = $(window).height();");
document.writeln("  t = $(document).scrollTop();");
document.writeln("  if(t > h){");
document.writeln("    $(\'#gotop\').show();");
document.writeln("  }else{");
document.writeln("    $(\'#gotop\').hide();");
document.writeln("  }");
document.writeln("}");
document.writeln("$(document).ready(function(e) {");
document.writeln("  b();");
document.writeln("  $(\'#gotop\').click(function(){");
document.writeln("    $(document).scrollTop(0); ");
document.writeln("  })");
document.writeln("  $(\'#code\').hover(function(){");
document.writeln("      $(this).attr(\'id\',\'code_hover\');");
document.writeln("      $(\'#code_img\').show();");
document.writeln("    },function(){");
document.writeln("      $(this).attr(\'id\',\'code\');");
document.writeln("      $(\'#code_img\').hide();");
document.writeln("  })");
document.writeln("  ");
document.writeln("});");
document.writeln("");
document.writeln("$(window).scroll(function(e){");
document.writeln("  b();    ");
document.writeln("})");
document.writeln("<\/script>");

$("#focus ul li a, .m-adsix li a, .sj_ad li a, .zwdiv ul li").find("img").after('<i class="icon_tg"></i>'); 